version: "2"
services:
   zookeeper:
      container_name: zookeeper
      image: seol0keti/zookeeper-with-data:1
      ports:
         - "2181:2181"
   kafka:
      container_name: kafka
      image: seol0keti/kafka-with-data:1
      depends_on:
         - zookeeper
      ports:
         - "9093:9093"
      expose:
         - "9092"
      environment:
         KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
         KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
         KAFKA_CREATE_TOPICS: "partition2Topic:2:1, partition3Topic:3:1, partition4Topic:4:1, partition5Topic:5:1, partition6Topic:6:1, partition7Topic:7:1, partition8Topic:8:1"
      volumes:
         - ./var/run/docker.sock:/var/run/docker.sock
   producer:
      container_name: producer
      image: seol0keti/producer-partition:1
      command: /bin/bash
      stdin_open: true
      tty: true
   consumer:
      container_name: consumer
      image: seol0keti/consumer-preproc-jar:1
      command: /bin/bash
      stdin_open: true
      tty: true
   redis:
      container_name: redis
      image: seol0keti/redis-jedis:1
      expose:
         - "6379"
