version: "2"
services:
   zookeeper:
      hostname: zookeeper
      container_name: zookeeper
      image: wurstmeister/zookeeper:3.4.6
      ports:
         - "2181:2181"
   kafka:
      hostname: kafka
      container_name: kafka
      image: wurstmeister/kafka:2.13-2.6.0
      depends_on:
         - zookeeper
      ports:
         - "9092:9092"
      environment:
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
         KAFKA_ADVERTISED_PORT: 9092
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
         - .:/var/run/docker.sock
   producer:
      container_name: producer
      image: seol0keti/node-producer:1
      command: /bin/bash
      stdin_open: true
      tty: true
   consumer:
      container_name: consumer
      image: seol0keti/java-consumer:1
      command: /bin/bash
      stdin_open: true
      tty: true
