version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.13-2.6.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
     - ./var/run/docker.sock:/var/run/docker.sock
  producer:
    container_name: producer
    image: seol0keti/node-producer:1
    command: /bin/bash
    stdin_open: true
    tty: true
  consumer:
    container_name: consumer
    image: seol0keti/java-consumer:1
    command: /bin/bash
    stdin_open: true
    tty: true
  redis:
    container_name: redis
    image: redis:6.2.1
    expose: 
      - "6379"
